import "../globals.scss";
import { Inter } from "next/font/google";
import Sidebar from "../components/Sidebar";
import { ConfigProvider, theme } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <section>
      <main className="h-screen pagesSidebar">
        <Sidebar />
        {children}
      </main>
    </section>
  );
}
